In [1]:
import tensorflow as tf

In [124]:
# for hide the warnings in python
import warnings
warnings.simplefilter("ignore")

Part 1 : Basics of tensorflow 

a. Graph in Tensorflow

Graph in tensor flow
Graph is the backbone of TensorFlow and every computation/operation/variables reside on the graph. 
Everything that happens in the code, resides on a default graph provided by TensorFlow. You can access this graph by:

In [6]:
graph = tf.get_default_graph()
print(graph)
graph.get_operations()

[]

In [12]:
for op in graph.get_operations():
    print(op.name)

In [15]:
print(graph.get_operations)
graph.get_operations()

<bound method Graph.get_operations of <tensorflow.python.framework.ops.Graph object at 0x000001DBCB56C320>>


[]

b. Tensorflow Session  

A graph is used to define operations, but the operations are only run within a session. Graphs and sessions are created independently of each other.
You can imagine graph to be similar to a blueprint, and a session to be similar to a construction site.Graph only defines the computations or builds the blueprint.
However, there are no variables, no values unless we run the graph or part of the graph within a session.

In [20]:
## creating the session 
sess = tf.Session()
b = 7
d = 10
c = 8
a = b + d
b = c + d
sess.close()

In [22]:
print(a)
print(b)

17
18


In [33]:
# build the graph
a = tf.constant(3)
b = tf.constant(7)
c = a * b

## lunch the tensorflow session 
sess = tf.Session()
print(sess.run(c))

21


In [45]:
sess = tf.Session()
print('Tensorflow', )
print('Keras',)
print('DeepLearning',)
sess.close()

Tensorflow
Keras
DeepLearning


In [63]:
##Whenever, you open a session, you need to remember to close it. Or you can use ‘with block’ like this.
f = tf.constant(2.5050)
## Advantage of with block is: session closes automatically at the end of the with block. 
#We use with block in most of our code and recommend you to do so too.

with tf.Session() as sess:
    print(sess.run(f))

2.505


c. Tensors in TensorFlow

TF holds data in Tensors which are similar to numPy multi-dimensional arrays(although they are different from numPy Arrays):
constants: are constants whose value can’t be changed. You can declare a constant like this:

In [64]:


a = tf.constant(1.0)
a
print(a)

Tensor("Const_16:0", shape=(), dtype=float32)


In [65]:
with tf.Session() as sess:
    print(sess.run(a))

1.0


varibales: it is similar to other languages it is assign the values to varibale like a = 7

In [70]:

b = tf.Variable(2.0, name = "test_var")
print(b)

<tf.Variable 'test_var_4:0' shape=() dtype=float32_ref>


In [74]:
## for tensor flow early version 
#init_op = tf.initialize_all_variables()
#init_op = tf.global_variables_initializer()

In [75]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(b))

2.0


In [76]:
## print operation on graph 
graph = tf.get_default_graph()
for op in graph.get_operations():
    print(op.name)

Const
Const_1
Const_2
Const_3
mul
Const_4
Const_5
mul_1
Const_6
Const_7
Const_8
Const_9
mul_3
Const_10
Const_11
Const_12
Const_13
Const_14
Const_15
Const_16
test_var/initial_value
test_var
test_var/Assign
test_var/read
test_var_1/initial_value
test_var_1
test_var_1/Assign
test_var_1/read
test_var_2/initial_value
test_var_2
test_var_2/Assign
test_var_2/read
test_var_3/initial_value
test_var_3
test_var_3/Assign
test_var_3/read
test_var_4/initial_value
test_var_4
test_var_4/Assign
test_var_4/read
init
init_1
init_2


placeholder :are tensors which are waiting to be initialized/fed.Placeholders are used for training data 
which is only fed when the code is actually run inside a session. What is fed to Placeholder is called feed_dict. 
Feed_dict are key value pairs for holding data:

In [83]:
a = tf.placeholder("float")
b = tf.placeholder("float")
y = tf.multiply(a, b)
   ##Earlier this used to be tf.mul which has changed with Tensorflow 1.0
 
 ##Typically we load feed_dict from somewhere else, 
 ##may be reading from a training data folder. etc
 ##For simplicity, we have put values in feed_dict here
feed_dict = {a:2, b:3}
with tf.Session() as sess:
    print(sess.run(y, feed_dict))

6.0


d. Device in TesorFlow

TensorFlow has very strong in-built capabilites to run your code on a gpu or a cpu or a cluster of gpu etc. It provides you options to select the device you want to run your code. However, this is not something that you need to worry about when you are just getting started. We shall write a separate tutorial on this later. So, here is the complete picture:

In [88]:
filename_queue = tf.train.string_input_producer(
    tf.train.match_filenames_once("./images/Tensorflow_Graph_0.jpg"))
image_reader = tf.WholeFileReader()

Part 2 : Tensorflow tutorial with simple examples

Create a random normal distribution
Use random_normal to create random values from a normal distribution. In this example, w is a variable which is of size 784*10 with random values with standard deviation 0.01.

In [103]:
w = tf.Variable(tf.random_normal([784*10], stddev = 0.01))
## for the with in block is not work for the variables 
print(w)

<tf.Variable 'Variable_8:0' shape=(7840,) dtype=float32_ref>


In [104]:
graph = tf.get_default_graph()
for op in graph.get_operations():
    print(op.name)

Const
Const_1
Const_2
Const_3
mul
Const_4
Const_5
mul_1
Const_6
Const_7
Const_8
Const_9
mul_3
Const_10
Const_11
Const_12
Const_13
Const_14
Const_15
Const_16
test_var/initial_value
test_var
test_var/Assign
test_var/read
test_var_1/initial_value
test_var_1
test_var_1/Assign
test_var_1/read
test_var_2/initial_value
test_var_2
test_var_2/Assign
test_var_2/read
test_var_3/initial_value
test_var_3
test_var_3/Assign
test_var_3/read
test_var_4/initial_value
test_var_4
test_var_4/Assign
test_var_4/read
init
init_1
init_2
Placeholder
Placeholder_1
Mul
Placeholder_2
Placeholder_3
Mul_1
Placeholder_4
Placeholder_5
Mul_2
Placeholder_6
Placeholder_7
Mul_3
Placeholder_8
Placeholder_9
Mul_4
matching_filenames/MatchingFiles/pattern
matching_filenames/MatchingFiles
matching_filenames
matching_filenames/Assign
matching_filenames/read
input_producer/Size
input_producer/Greater/y
input_producer/Greater
input_producer/Assert/Const
input_producer/Assert/Assert/data_0
input_producer/Assert/Assert
input_produc

In [125]:
## Reduce the mean, calculate the mean of arry 
b = tf.Variable([10, 20, 30, 40, 50, 60], name = 't')
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(tf.reduce_mean(b)))
    print(sess.run(tf.reduce_min(b)))
    print(sess.run(tf.reduce_max(b)))
    print(sess.run(tf.reduce_prod(b)))
    print(sess.run(tf.reduce_sum(b)))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
35
10
60
720000000
210


In [129]:
## ArgMax: Very similar to python argmax. Gets you the maximum value from atensor along the specified axis.
a = [[0.1, 0.2, 0.3],[20, 2, 3]]
b = tf.Variable(a, name = 'b')
with tf.Session() as sess:
    (sess.run(tf.initialize_all_variables()))
    print(sess.run(tf.argmax(b, 1)))
    ## the output shows the index of array

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[2 0]


Linear Regression exercise

Problem statement: In linear regression, you get a lot of data-points and try to fit them on a straight line. For this example, we will create 100 datapoints and try to fit them into a line.

a) Creating the training data :

trainX has values between -1 and 1, and trainY has 3 times the trainX and some randomness.



In [133]:
import numpy as np
trainX = np.linspace(-1, 1, 101)
print(trainX)
trainY = 3*trainX + np.random.randn(*trainX.shape) * 0.33
print( trainY)

[-1.   -0.98 -0.96 -0.94 -0.92 -0.9  -0.88 -0.86 -0.84 -0.82 -0.8  -0.78
 -0.76 -0.74 -0.72 -0.7  -0.68 -0.66 -0.64 -0.62 -0.6  -0.58 -0.56 -0.54
 -0.52 -0.5  -0.48 -0.46 -0.44 -0.42 -0.4  -0.38 -0.36 -0.34 -0.32 -0.3
 -0.28 -0.26 -0.24 -0.22 -0.2  -0.18 -0.16 -0.14 -0.12 -0.1  -0.08 -0.06
 -0.04 -0.02  0.    0.02  0.04  0.06  0.08  0.1   0.12  0.14  0.16  0.18
  0.2   0.22  0.24  0.26  0.28  0.3   0.32  0.34  0.36  0.38  0.4   0.42
  0.44  0.46  0.48  0.5   0.52  0.54  0.56  0.58  0.6   0.62  0.64  0.66
  0.68  0.7   0.72  0.74  0.76  0.78  0.8   0.82  0.84  0.86  0.88  0.9
  0.92  0.94  0.96  0.98  1.  ]
[-2.85100722 -2.88408194 -2.86744544 -2.54420221 -2.46497759 -3.09177861
 -2.40807883 -2.11884072 -2.81401613 -2.61729023 -2.23389517 -2.55915214
 -1.95252787 -2.30949664 -2.14975059 -2.38240891 -2.51327309 -1.80972564
 -1.90798707 -1.61005492 -1.78316153 -1.27787256 -1.47537819 -1.26672551
 -1.23415718 -1.25731585 -1.6269146  -1.12676757 -1.22379681 -0.88264821
 -0.60431461 -0.53786

b) placeholder

In [144]:
X = tf.placeholder("float")
Y = tf.placeholder("float")

c) Modeling 

Linear regression model is y_model=w*x and we have to calculate the value of w through our model. Let’s initialize w to 0 and create a model to solve this problem. We define the cost as square of (Y-y_model). TensorFlow comes with many optimizers that calculate and update the gradients after each iteration while trying to minimize the specified cost. We are going to define the training operation as changing the values using GradientDescentOptimizer to minimize cost with a learning rate of 0.01. Later we will run this training operation in a loop.

In [147]:
w = tf.Variable(0.0, name = "weights")
y_model = tf.multiply(X, w)
cost = (tf.pow(Y - y_model, 2))
#train_op = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

d) training

Till this point, we have only defined the graph. No computation has happened.

None of the TensorFlow variables have any value. In order to run this graph, we need to create a Session and run. Before that we need to create the init_op to initialize all variables:

In [148]:
init = tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [155]:
with tf.Session() as sess:
    sess.run(init)

In [158]:
#for i in range(100):
    #for (x, y) in zip(trainX, trainY):
        #sess.run(train_op, feed_dict= {X:x, Y:y})
    #print(sess.run(w))

In [157]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(w))

0.0


In [159]:
## basic program by using tensorflow 
import tensorflow as tf

In [160]:
## building a graph
## to create two scource operations which will output number willdefine two constants
a = tf.constant([2])
b = tf.constant([3])

In [171]:
c = tf.add(a, b)
c1 = tf.multiply(a,b)
with tf.Session() as sess:
    print(sess.run(c))
    with tf.Session() as sess:
        print(sess.run(c1))

[5]
[6]


In [172]:
c2 = tf.divide(b, a)
session = tf.Session()
result = session.run(c2)
print(result)
session.close()

[ 1.5]


In [189]:
c = tf.constant('Hello World', name = 'string')
session = tf.Session()
result = session.run(c)
print(result)
session.close()

b'Hello World'


Defining multidimensional arrays using tensorflow

In [209]:
matrix_one = tf.constant([[2,3],[3,4]])
matrix_two = tf.constant([[3,4],[5,6]])

first_operation = tf.multiply(matrix_one,matrix_two)
with tf.Session() as sess:
    result = sess.run(first_operation)
    print("Defined using tensor flow function:")
    print(result)

Defined using tensor flow function:
[[ 6 12]
 [15 24]]


In [213]:
# variable example
state = tf.Variable(0)
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)\

init_op = tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [216]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [220]:
a = tf.constant([2])
b = tf.constant([7])
c = tf.add(a,b)
sess = tf.Session()
result = sess.run(c)
print(result)
sess.close()

[9]


In [221]:
with tf.Session() as sess:
    result = sess.run(c)
    print(result)

[9]


What is the meaninhg of tensorflow?

In TensorFlow all data is passed between operations in a computation graph, and these are passed in the form of Tensors, hence the name of TensorFlow. 

In [227]:
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session() as session:
    result = session.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % (result,))
    result = session.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % (result))
    result = session.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % (result))
    result = session.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % (result))

Scalar (1 entry):
 [2] 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [228]:
graph = tf.get_default_graph()
print(graph)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'mul_1' type=Mul>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'mul_3' type=Mul>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Const_12' type=Const>,
 <tf.Operation 'Const_13' type=Const>,
 <tf.Operation 'Const_14' type=Const>,
 <tf.Operation 'Const_15' type=Const>,
 <tf.Operation 'Const_16' type=Const>,
 <tf.Operation 'test_var/initial_value' type=Const>,
 <tf.Operation 'test_var' type=VariableV2>,
 <tf.Operation 'test_var/Assign' type=Assign>,
 <tf.Operation 'test_var/read' type=Identity>,
 <tf.Operation 'test_var_1/initial_value' type=Const>,
 <t

In [229]:
state = tf.Variable(0)

In [230]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

In [231]:
init_op = tf.global_variables_initializer()

In [234]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


Placeholder:

if you want to feed the data to tensorflow model from outside a model, you will need to use placeholder
So what are these placeholders and what do they do?

Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to, you can create them using 
tf.placeholder(datatype), where datatype specifies the type of data (integers, floating points, strings, booleans) along with its precision (8, 16, 32, 64) bits.

In [241]:
## creating the place holder 
a = tf.placeholder(tf.float32)
b = a * 2
with tf.Session() as sess:
    result = sess.run(b, feed_dict = {a:3.5})
    print(result)

7.0


In [244]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print(result)

[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]


For sigmoid:

tf.nn.sigmoid is an activiation function, it's a little more complicated, but this function helps learning models to evaluate what kind of information is good or not.